# Generated by Django 3.2.9 on 2022-01-12 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220111_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_admin',
        ),
    ]
